// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Application: typeof import('./src/components/Application/Application.vue')['default']
    BasicForm: typeof import('./src/components/Form/src/BasicForm.vue')['default']
    BasicModal: typeof import('./src/components/Modal/src/basicModal.vue')['default']
    BasicUpload: typeof import('./src/components/Upload/src/BasicUpload.vue')['default']
    ColumnSetting: typeof import('./src/components/Table/src/components/settings/ColumnSetting.vue')['default']
    CountTo: typeof import('./src/components/CountTo/CountTo.vue')['default']
    EditableCell: typeof import('./src/components/Table/src/components/editable/EditableCell.vue')['default']
    Lockscreen: typeof import('./src/components/Lockscreen/Lockscreen.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    Recharge: typeof import('./src/components/Lockscreen/Recharge.vue')['default']
    Table: typeof import('./src/components/Table/src/Table.vue')['default']
    TableAction: typeof import('./src/components/Table/src/components/TableAction.vue')['default']
  }
}

export { }
